### ISSUE TITLE
iOS: App is stuck on UAE PASS loading webview page when redirected back from UAE PASS app after declining request

### ISSUE THREAD

**Issue by Yousafzubair991** [vyshakh/react-native-uaepass#13]
Hi @vyshakh ,
Thank you for providing the package, this made our lives much easier.
I am facing a minor issue but that issue is crucial for the app approval from the UAE PASS team.

Scenario:
The user has UAE PASS installed on their device (iOS only)
The user clicks login and is redirected to UAE PASS for authorization.
The user declines the authorization request.
The user is redirected to our app but the UAE PASS webview is now stuck on the loading page (screenshot attached) 

Other declining scenarios (Works perfectly fine)

**iOS:** If the app is not installed on the device.
**Android:** If the app is installed on the device.
**Android:** If the app is not installed on the device.

Please let me know if I'm missing something.

Best Regards.

![IMG_1045](https://github.com/user-attachments/assets/e3e7178e-0725-4cf9-94a6-06f55c562865)

**Comment by vyshakh** [comment]
@Yousafzubair991  Thank you for reporting the issue. I have pushed a fix and released version 1.0.15. Please give it a try.

**Comment by Yousafzubair991** [comment]
Hi @vyshakh, Thank you for pushing a quick fix, but unfortunately, the issue persists on my end. Upon declining the cancellation request from the UAE PASS app, the app is stuck in the loading modal until I slide it down and close it manually.

**Comment by vyshakh** [comment]
@Yousafzubair991 I found the issue: the UAEpass library is using a hardcoded scheme for iOS. I've updated the README and released version 1.0.16. Please use the following successHost and failureHost values:
```
successHost: 'uaePassSuccess'  
failureHost: 'uaePassFail'
```

**Comment by Yousafzubair991** [comment]
@vyshakh  the issue is now fixed, Thank you for your response, I appreciate 🙌
